### ISSUE TITLE
Issues introduced with merge of pull request #5

### ISSUE THREAD

**Issue by srhenning** [mdoerfel/emf4cpp#1]
The merge of the pull request #5 on the original repository https://github.com/catedrasaes-umu/emf4cpp introduced two issues in the emf4cpp library.

1. In org.csu.emf4cpp.generator/src/template/PackageImpl.xpt a new function 'getFQN2()' is used but this function is defined nowhere.
2. In org.csu.emf4cpp.generator/src/template/EClassImplCPP.xpt 'EAllStructuralFeatures' was erroneously replaced by 'EStructuralFeatures' in the loop constructs of all setters/getters (eGet, eSet, eIsSet, eUnset). This implies that no base class features can be set/get anymore and should be reverted.

**Comment by srhenning** [comment]
Issue was solved in branch issue-1.

**Comment by mdoerfel** [comment]
The upstream project reverted pull request #5.
