### ISSUE TITLE
Segmentation fault due to null pointer dereference if no root element found

### ISSUE THREAD

**Issue by rpiskun** [mdoerfel/emf4cpp#5]
Hello Guys,

First of all I would thank you for your awesome EMF tool! 
I have faced with an issue. When input file (in my case XML) is truncated and no all header items are present in it, EMF parser fails with segmentation fault. It happens due to XMLHandler::getRootElement() returns NULL but XMLResource::doLoad() doesn't check return value:
```
::ecore::EObject_ptr root = handler.getRootElement();  // returns NULL
root->_initialize();                                   // no check for NULL - segmentation fault
```

Thank you in advance,
Roman

**Comment by srhenning** [comment]
Hi Roman,

first of all many thanks for the praising words and the hint on the missing null pointer treatment. We will add a corresponding null pointer handling as soon as possible.

Many greetings
Soeren
